version: '3.8' # или ниже

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  jupyter-spark:
    image: my-jupyter-spark
    container_name: jupyter_spark
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work # Локальная папка для работы
      - ./postgresql-42.6.0.jar:/opt/spark/jars/postgresql-42.6.0.jar # Монтирование JAR-файла
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    restart: unless-stopped
